import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const dom=new JSDOM('<!doctype html><html><head><meta name="description" content=""></head><body><div id="root"></div></body></html>',{url:'https://clearfincalc.com/'});
for(const k of ['window','document','HTMLElement','HTMLInputElement','Event','MouseEvent','PopStateEvent','localStorage'])globalThis[k]=dom.window[k];
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
globalThis.fetch=async()=>({ok:false,json:async()=>({})});
globalThis.ResizeObserver=class{observe(){} unobserve(){} disconnect(){}};
dom.window.HTMLElement.prototype.scrollIntoView=function(){};
dom.window.matchMedia=()=>({matches:false,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});
const {createElement,act}=await import('react');
const {createRoot}=await import('react-dom/client');
const {default:App}=await import('../audit-ssr/App.js');
const root=createRoot(document.getElementById('root'));
const settle=async(fn)=>{await act(async()=>{await fn?.();await new Promise(r=>setTimeout(r,40));});};
const click=async(el)=>{assert.ok(el,'Target exists');await settle(()=>el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true})));};
await settle(()=>root.render(createElement(App))); await settle();
assert.equal(document.querySelectorAll('#calculators a[href^="?tool="]').length,13);
assert.equal(document.querySelectorAll('#insights a[href^="?article="]').length,30);
assert.equal(document.querySelectorAll('a[href^="#apply-"]').length,0);
assert.equal(document.querySelector('form input[type="email"]'),null);
const calculatorRoutes=['emi','sip','tds','customs','eligibility','personal-loan','home-loan','tax','salary','gst','fd','retirement','savings-goal'];
const calculatorTitles=[]; const calculatorDescriptions=[];
for(const tool of calculatorRoutes){
  await settle(()=>{window.history.pushState({},'',`/?tool=${tool}`);window.dispatchEvent(new PopStateEvent('popstate'));});
  assert.equal(document.querySelector('link[rel="canonical"]').href,`https://clearfincalc.com/?tool=${tool}`,`canonical for ${tool}`);
  assert.match(document.title,/\| ClearFinCalc$/u,`title for ${tool}`);
  assert.ok(document.title.length>15,`non-empty title for ${tool}`);
  const description=document.querySelector('meta[name="description"]')?.content ?? '';
  assert.ok(description.length>=70 && description.length<=180,`description length for ${tool}: ${description.length}`);
  assert.equal(document.querySelectorAll('h1').length,1,`one primary heading for ${tool}`);
  assert.ok(document.querySelector('#calculator-math'),`formula present without tab interaction for ${tool}`);
  assert.ok(document.querySelector('#calculator-faqs'),`FAQs present without tab interaction for ${tool}`);
  assert.ok(!document.querySelector('#calculator-guide').textContent.includes('###'),`headings rendered for ${tool}`);
  calculatorTitles.push(document.title); calculatorDescriptions.push(description);
}
assert.equal(new Set(calculatorTitles).size,calculatorRoutes.length,'calculator titles are unique');
assert.equal(new Set(calculatorDescriptions).size,calculatorRoutes.length,'calculator descriptions are unique');
const sitemap=readFileSync(new URL('../public/sitemap.xml',import.meta.url),'utf8');
const builtSitemap=readFileSync(new URL('../dist/sitemap.xml',import.meta.url),'utf8');
assert.equal(builtSitemap,sitemap,'production build preserves sitemap.xml');
const sitemapCalculatorRoutes=[...sitemap.matchAll(/<loc>https:\/\/clearfincalc\.com\/?\?tool=([^<]+)<\/loc>/gu)].map(match=>decodeURIComponent(match[1]));
assert.deepEqual([...sitemapCalculatorRoutes].sort(),[...calculatorRoutes].sort(),'sitemap includes each calculator route exactly once');
await click(document.querySelector('a[href="?tool=emi"]'));await settle();
assert.ok(document.querySelector('#emi-loan-tenure'));
assert.equal(document.querySelector('link[rel="canonical"]').href,'https://clearfincalc.com/?tool=emi');
const input=document.querySelector('#emi-loan-tenure');
const nativeSetter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;
await settle(()=>{nativeSetter.call(input,'0');input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));});
assert.equal(input.getAttribute('aria-invalid'),'true');assert.ok(document.querySelector('[role="alert"]'));assert.ok(!document.body.textContent.includes('₹NaN'));
await click(document.querySelector('a[href="?article=income-tax-basics"]'));await settle();
assert.equal(document.querySelector('link[rel="canonical"]').href,'https://clearfincalc.com/?article=income-tax-basics');
assert.equal(document.querySelectorAll('[role="dialog"]').length,1);
assert.match(document.title,/Income Tax Basics.*ClearFinCalc Insights/);
assert.equal(document.querySelectorAll('h1').length,1);
await settle(()=>{window.history.pushState({},'','/?tool=sip');window.dispatchEvent(new PopStateEvent('popstate'));});await settle();
assert.equal(document.querySelectorAll('[role="dialog"]').length,0);assert.ok(document.querySelector('#sip-monthly-investment'));
await click(document.querySelector('a[href="?tool=tax"]'));await settle();
assert.equal(document.querySelector('#tax-deductions').value,'75000');assert.equal(document.querySelector('#tax-deductions').disabled,true);assert.ok(document.body.textContent.includes('97,500'));
const articleLinks=[...document.querySelectorAll('#insights a[href^="?article="]')].map(a=>a.getAttribute('href'));
const articleTitles=[];
for(const href of articleLinks){
  await settle(()=>{window.history.pushState({},'',`/${href}`);window.dispatchEvent(new PopStateEvent('popstate'));});
  assert.match(document.title,/\| ClearFinCalc Insights$/);
  assert.equal(document.querySelector('link[rel="canonical"]').href,`https://clearfincalc.com/${href}`);
  assert.equal(document.querySelectorAll('h1').length,1);
  articleTitles.push(document.title);
}
assert.equal(new Set(articleTitles).size,30,'unique article titles survive parent metadata effects');
await settle(()=>{window.history.pushState({},'','/');window.dispatchEvent(new PopStateEvent('popstate'));});
assert.equal(document.title,'ClearFinCalc - Clear Calculations. Smarter Decisions.');
await settle(()=>root.unmount());dom.window.close();
console.log('PASS: 13 calculator links and unique title, description and canonical metadata; sitemap route coverage; 30 article links; placeholders removed; invalid EMI input; route synchronization; tax defaults.');
